USE airticket;

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE MealReservation;
TRUNCATE TABLE TicketSale;
TRUNCATE TABLE FlightSegment;
TRUNCATE TABLE Flight;
TRUNCATE TABLE MealOption;
TRUNCATE TABLE `User`;
TRUNCATE TABLE Aircraft;
TRUNCATE TABLE Airport;
TRUNCATE TABLE City;
SET FOREIGN_KEY_CHECKS = 1;
